# version: '2.2'
# services:
#   forwardproxy:
#     container_name: forwardproxy
#     image: mitmproxy/mitmproxy
#     command: mitmdump
#     volumes:
#       - ${CONFIG_PATH}/config.yaml:/home/mitmproxy/.mitmproxy/config.yaml
#     ports:
#       - "8888:8080"
#     restart: always 

version: '2.2'
services:
  forwardproxy:
    container_name: fproxy
    image: demanproxy:latest
    volumes:
      - ${CONFIG_PATH}/config.yaml:/usr/fproxy/config.yml
    ports:
      - "8888:8080"
      - "7777:7777"
    restart: always
    environment:
      - INSTANCES=2
      - MON_HTTP_PORT=8888
      - PROXY_HTTP_PORT=8080
      - CONFIG_FILE=/usr/fproxy/config.yml
